name: Build LaTeX document
on:
  push:
    branches:
      - main
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    env:
      PAPER: ${{ github.event.repository.name }}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Download LaTeX styles
        run: |
          curl -OL https://github.com/dpo/latex-styles/archive/refs/heads/master.zip
          curl -OL https://www.siam.org/Portals/0/Macros/Standard/siamart_190516.zip
          unzip master.zip
          unzip siamart_190516.zip -d siam-styles
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            ${{ env.PAPER }}.tex
          working_directory: paper
          extra_system_packages: "git patch"
          latexmk_shell_escape: true
        env:
          TEXINPUTS: ".:$PWD/../siam-styles:$PWD/../latex-styles-master/styles//:"
          BSTINPUTS: ".:$PWD/../latex-styles-master/styles/common"
          BIBINPUTS: ".:$PWD/../latex-styles-master/share"
      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: |
            paper/${{ env.PAPER }}.pdf
      - name: Publish artifacts
        if: ${{ github.event_name == 'pull_request' }}
        uses: gavv/pull-request-artifacts@v1.0.0
        with:
          commit: ${{ github.event.pull_request.head.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          artifacts-branch: pdfs
          artifacts: |
            paper/${{ env.PAPER }}.pdf
